0. 입출력 및 사칙연산/src/BOJ_17425_bmk.java, 0. 입출력 및 사칙연산/src/BOJ_17427_bmk.java, 0. 입출력 및 사칙연산/src/BOJ_1929_bmk.java, 0. 입출력 및 사칙연산/src/BOJ_1978_bmk.java, 0. 입출력 및 사칙연산/src/BOJ_2609_bmk.java, 0. 입출력 및 사칙연산/src/BOJ_6588_bmk.java
> 아니오
<br>
7
<br>
- 구현에서 테스트 케이스가 맞게 나오는 것 까지는 쉬웠으나,
- 시간 복잡도에서 문제가 발생해, 시간 초과가 계속 발생하는 것이 어려웠습니다.
- 특정 공식들을 알고 있지 않다면 문제를 푸는 것이 매우 어려웠습니다.
<br>
시간 복잡도를 줄일 수 있는 방법과 해당 방법이 왜 시간 복잡도가 적은지 알고 싶습니다.
<br>
=> [8월 / 1주차] 입출력 및 사칙연산_방민규_ver1

.idea/SSAFY12th-algo-study.iml, .idea/uiDesigner.xml, 0. 입출력 및 사칙연산/src/BOJ_1037_Wooseok.java, 0. 입출력 및 사칙연산/src/BOJ_10430_Wooseok.java, 0. 입출력 및 사칙연산/src/BOJ_17425_Wooseok.java, 0. 입출력 및 사칙연산/src/BOJ_17427_Wooseok.java, 0. 입출력 및 사칙연산/src/BOJ_1929_Wooseok.java, 0. 입출력 및 사칙연산/src/BOJ_1978_Wooseok.java, 0. 입출력 및 사칙연산/src/BOJ_2609_Wooseok.java, 0. 입출력 및 사칙연산/src/BOJ_4375_Wooseok.java, 0. 입출력 및 사칙연산/src/BOJ_6588_Wooseok.java
> 네
<br>
전체 난이도 평균 : 4/10
<br>
- 시간 초과로 인한 실패 (소수구하기) 
<br>
https://velog.io/@max9106/Algorithm-%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98-%EC%B2%B4
(ex. 참고할만한 개념) -->  에라토스테네스의 체 
<br>
=> [8월/1주차] 입출력 및 사칙연산_송우석_ver1

.idea/SSAFY12th-algo-study.iml, 1. 브루트포스/BOJ1107/BOJ1107_soomin.java, 1. 브루트포스/BOJ1476/BOJ1476_soomin.java, 1. 브루트포스/BOJ2309/BOJ2309_soomin.java, 1. 브루트포스/BOJ3085/BOJ3085_soomin.java
> 넹
<br>
5
<br>
- 리모컨 문제에서 엣지 케이스 찾기, 시간복잡도 어림하기
<br>
조합, 순열, 구현
<br>
=> [8월 4주차] 1.브루트포스_김수민_ver1

1. 브루트포스/BOJ1476/BOJ1476_hyunjin.java, 1. 브루트포스/BOJ2309/BOJ2309_hyunjin.java, 1. 브루트포스/BOJ3085/BOJ3085_hyunjin.java
> 아니요.. 
<br>
- 8
<br>
- 머리가 안 돌아가요... 
- boj1476은 답은 틀리게 나오는데.. 어디가 틀렸는지를 못 찾겠어서 일단 그냥 올려봅니다..
<br>
<br>
=> [8월/4주차] 1.브루트포스_김현진_ver1

1. 브루트포스/BOJ1107/BOJ1107_minkyu.java, 1. 브루트포스/BOJ1476/BOJ1476_minkyu.java, 1. 브루트포스/BOJ2309/BOJ2309_minkyu.java, 1. 브루트포스/BOJ3085/BOJ3085_minkyu.java
> 네
<br>
3
<br>
- 문제에 조건을 찾는 것이 어려웠습니다. 
<br>
<br>
=> [8월/4주차] 1.브루트포스_방민규_ver1

1. 브루트포스/BOJ2309/BOJ2309_mirim.java
=> [8월/4주차]1.브루트포스_이미림_ver1

1. 브루트포스/BOJ1107/BOJ1107_mingyung.java, 1. 브루트포스/BOJ1476/BOJ1476_mingyung.java, 1. 브루트포스/BOJ2309/BOJ2309_mingyung.java, 1. 브루트포스/BOJ3085/BOJ3085_mingyung.java, 6. 백트래킹/BOJ2992/BOJ2992_mingyung.java, 6. 백트래킹/BOJ9742/BOJ9742_mingyung.java
> 네
<br>
8
- 백트래킹 하는 게 익숙치 않습니다...
<br>
<br>
=> [9월/1주차] 백트래킹_월말평가 대비_박민경_ver1

6. 백트래킹/BOJ11050/BOJ11050_hyunjin.java, 6. 백트래킹/BOJ16395/BOJ16395_hyunjin.java, 6. 백트래킹/BOJ2992/BOJ2992_hyunjin.java, 6. 백트래킹/BOJ9742/BOJ9742_hyunjin.java
> 아니요
<br>
8
<br>
- 메모리초과...!!! 시간 초과...!
- 순열을 활용하여 백트래킹과 브루트포스로 문제를 해결하고자 하니 계속해서 재귀함수 호출이 일어나 발생한 메모리 초과 문제가 발생함.
<br>
<br>
=> [9월/1주차] 백트래킹_월말평가 대비_김현진_ver1

SW역량평가_A형 대비/SWEA1767/SWEA1767_soomin.java, SW역량평가_A형 대비/SWEA2117/SWEA2117_soomin.java, SW역량평가_A형 대비/SWEA5656/SWEA5656_soomin.java
> 네
<br>
> 5
<br>
> 구현에서 엣지케이스 찾기
- 
<br>
<br>
=> [9월/1주차] SW역량테스트 A형대비_김수민_ver1

SW역량평가_A형 대비/BOJ20056/BOJ20056_minkyu.java, SW역량평가_A형 대비/BOJ20057/BOJ20057_minkyu.java, SW역량평가_A형 대비/BOJ20058/BOJ20058_minkyu.java, SW역량평가_A형 대비/SWEA1767/SWEA1767_minkyu.java, SW역량평가_A형 대비/SWEA2117/SWEA2117_minkyu.java, SW역량평가_A형 대비/SWEA5656/SWEA5656_minkyu.java
=> [9월/1주차] SW역량테스트 A형대비_방민규_ver1

1. 브루트포스/BOJ14500/BOJ14500_mingyung.java, 1. 브루트포스/BOJ1748/BOJ1748_mingyung.java, 1. 브루트포스/BOJ6064/BOJ6064_mingyung.java, 1. 브루트포스/BOJ9095/BOJ9095_mingyung.java
> 4문제 중 3문제 풀었습니다!
<br>
아직까진 4....?
<br>
- 어떻게 접근할지 생각하는 부분이 어려웠습니다..
<br>
<br>
=> [9월/2주차] 1.브루트포스_박민경_ver1

1. 브루트포스/BOJ14500/BOJ14500_soomin.java, 1. 브루트포스/BOJ1748/BOJ1748_soomin.java, 1. 브루트포스/BOJ6064/BOJ6064_soomin.java, 1. 브루트포스/BOJ9095/BOJ9095_soomin.java
> 네
<br>
> 5
<br>
- 6064번 유효하지 않은 조건을 어떻게 끝내야 하는지 판단하는 것이 어려웠습니다. 전반적으로 구현보다 아이디어가 필요한 문제들이었던 것 같습니다.
<br>
<br>
=> [9월/2주차] 1. 브루트포스_김수민_ver1

1. 브루트포스/BOJ1748/BOJ1748_hyunjin.java, 1. 브루트포스/BOJ6064/BOJ6064_hyunjin.java, 1. 브루트포스/BOJ9095/BOJ9095_hyunjin.java
> 아니요
<br>
8
<br>
- 중복순열 구하는 문제 아직 잘 이해가 안 됩니당,,ㅠㅠ
<br>
<br>
=> [9월/2주차] 1. 브루트포스_김현진_ver1

1. 브루트포스/BOJ14500/boj14500_minkyu.java, 1. 브루트포스/BOJ1748/boj1748_minkyu.java, 1. 브루트포스/BOJ9095/boj9095_minkyu.java
> 아니요
<br>
5
<br>
- 카잉 달력의 시간 복잡도 문제가 어려웠습니다.
<br>
<br>
=> [9월/2주차] 1.브루트포스_방민규_ver1

0. 입출력 및 사칙연산/src/BOJ1037/BOJ_1037_dohee.java, 0. 입출력 및 사칙연산/src/BOJ10430/BOJ_10430_dohee.java, 0. 입출력 및 사칙연산/src/BOJ17425/BOJ17425_dohee.java, 0. 입출력 및 사칙연산/src/BOJ17425/BOJ_17425_dohee.java, 0. 입출력 및 사칙연산/src/BOJ17427/BOJ_17427_dohee.java, 0. 입출력 및 사칙연산/src/BOJ1929/BOJ1929_dohee.java, 0. 입출력 및 사칙연산/src/BOJ1978/BOJ_1978_dohee.java, 0. 입출력 및 사칙연산/src/BOJ2609/BOJ_2609_dohee.java, 0. 입출력 및 사칙연산/src/BOJ4375/BOJ_4375_dohee.java, 1. 브루트포스/BOJ14500/BOJ14500_dohee.java, 1. 브루트포스/BOJ1748/BOJ1748_dohee.java, 1. 브루트포스/BOJ2309/BOJ2309_dohee.java, 1. 브루트포스/BOJ6064/BOJ6064_dohee.java, 1. 브루트포스/BOJ9095/BOJ9095_dohee.java
> 네
<br>
9095번은 풀었었는데, 파이썬 코드라서 다음번에 자바로 변환해서 올리겠습니다. DP로 구현했습니다.
<br>
7
- 
<br>
<br>
이전 'Dobee-Kim' 브랜치 관리를 잘못하여, 커밋 히스토리가 많이 달라져서 새로 팠습니다.
주말 중으로 파일과 브랜치 정리해서 다시 올리겠습니다.
=> [9월/2주차] 1. 브루트포스_김도희_ver1

1. 브루트포스/BOJ14501/BOJ14501_soomin.java, 1. 브루트포스/BOJ14889/BOJ14889_soomin.java, 1. 브루트포스/BOJ15661/BOJ15661_soomin.java, 1. 브루트포스/BOJ1759/BOJ1759_soomin.java, 1. 브루트포스/BOJ2529/BOJ2529_soomin.java
> 네
<br>
> 5
<br>
- String.fromat 형식 지정자 다 잊어버려서 출력 형식 맞추는 데 약간 힘들었습니다.
<br>
<br>
=> [9월/3주차] 1. 브루트포스_김수민_ver1

1. 브루트포스/BOJ1107/BOJ1107_dohee.java, 1. 브루트포스/BOJ14501/BOJ14501_dohee.java, 1. 브루트포스/BOJ1476/BOJ1476_dohee.java, 1. 브루트포스/BOJ14889/BOJ14889_dohee.java, 1. 브루트포스/BOJ15661/BOJ15661_dohee.java, 1. 브루트포스/BOJ1759/BOJ1759_dohee.java, 1. 브루트포스/BOJ2529/BOJ2529_dohee.java, 1. 브루트포스/BOJ3085/BOJ3085_dohee.java
> 네
<br>
네
<br>
7
- 
<br>
<br>
=> [9월/3주차] 1. 브루트포스_김도희

7. DP/BOJ11726/BOJ11726_mirim.java, 7. DP/BOJ1463/BOJ1463_mirim.java, 7. DP/BOJ2579/BOJ2579_mirim.java
> 네
<br>
6
<br>
- 사소한 부분을 자꾸 놓쳐서 시간이 좀 걸렸당
<br>
<br>
=> [10월/ 1주차] 7.DP_이미림_ver1

7. DP/BOJ11726/BOJ11726_mingyung.java, 7. DP/BOJ1463/BOJ1463_mingyung.java, 7. DP/BOJ2579/BOJ2579_mingyung.java
> DP 문제 풀었습니다.
<br>
8
<br>
- DP는 괜찮았는데...ㅠㅠ
<br>
<br>
=> [10월/ 1주차] 7.DP_박민경_ver1

7. DP/BOJ11726/BOJ11726_dohee.java, 7. DP/BOJ1463/BOJ1463_dohee.java
=> [10월/ 1주차] 7.DP_김도희_ver1

0. 입출력 및 사칙연산/BOJ13458/BOJ13458_mingyung.java, 5. 그래프/5-1. DFS, BFS/SWEA1226/SWEA1226_mingyung.java, 5. 그래프/5-1. DFS, BFS/SWEA1953/SWEA1953_mingyung.java, 5. 그래프/5-1. DFS, BFS/SWEA22654/SWEA22654_mingyung.java
> 아니요.....
<br>
7
<br>
- 그냥 어려웠따
<br>
<br>
=> [10월/ 2주차] 5.그래프_박민경_ver1

1. 브루트포스/BOJ14888/BOJ14888_minkyu.java, 1. 브루트포스/BOJ14889/BOJ14889_minkyu.java, 1. 브루트포스/BOJ15683/BOJ15683_minkyu.java, 2. 그리디/BOJ11000/BOJ11000_minkyu.java, 2. 그리디/BOJ1339/BOJ1339_minkyu.java, 2. 그리디/BOJ16496/BOJ16496_minkyu.java, 2. 그리디/BOJ1715/BOJ1715_minkyu.java, 2. 그리디/BOJ1744/BOJ1744_minkyu.java, 3. 구현 및 시뮬레이션/BOJ14503/BOJ14503_minkyu.java, 3. 구현 및 시뮬레이션/BOJ14890/BOJ14890_minkyu.java, 3. 구현 및 시뮬레이션/BOJ14891/BOJ14891_minkyu.java, 4. 이진탐색/BOJ12738/BOJ12738_minkyu.java, 4. 이진탐색/BOJ1300/BOJ1300_minkyu.java, 4. 이진탐색/BOJ1939/BOJ1939_minkyu.java, 4. 이진탐색/BOJ2467/BOJ2467_minkyu.java
> 네
<br>
5
<br>
-  이진탐색을 적용할 부분을 찾는 게 어려웠습니다.
<br>
<br>
=> [10월/4주차] 그리디_방민규_ver1

2. 그리디/BOJ11047/BOJ11047_hyunjin.java, 2. 그리디/BOJ11399/BOJ11399_hyunjin.java, 2. 그리디/BOJ1931/BOJ1931_hyunjin.java, 2. 그리디/BOJ2839/BOJ2839_hyunjin.java, 3. 구현 및 시뮬레이션/BOJ14503/BOJ14503_hyunjin.java, 3. 구현 및 시뮬레이션/BOJ14891/BOJ14891_hyunjin.java, 4. 이진탐색/BOJ10815/BOJ10815_hyunjin.java, 4. 이진탐색/BOJ10816/BOJ10816_hyunjin.java, 4. 이진탐색/BOJ1920/BOJ1920_hyunjin.java, 4. 이진탐색/BOJ2776/BOJ2776_hyunjin.java, 4. 이진탐색/BOJ2805/BOJ2805_hyunjin.java
> 아니요
<br>
- 8 
<br>
- 이분탐색이 일어나는 과정을 이해하는게 어려웠습니다
<br>
<br>
=> [10월/3주차] 이분탐색_김현진_ver1

0. 입출력 및 사칙연산/BOJ13458/BOJ13458_dohee.java, 1. 브루트포스/BOJ14888/BOJ14888_dohee.java, 3. 구현 및 시뮬레이션/BOJ14499/BOJ14499_dohee.java, 4. 이진탐색/BOJ10815/BOJ10815_dohee.java, 4. 이진탐색/BOJ10816/BOJ10816_dohee.java, 4. 이진탐색/BOJ2776/BOJ2776_dohee.java, 4. 이진탐색/BOJ2805/BOJ2805_dohee.java, 5. 그래프/5-1. DFS, BFS/BOJ14502/BOJ14502_dohee.java, 5. 그래프/5-1. DFS, BFS/SWEA1226/SWEA1226_dohee.java, 5. 그래프/5-1. DFS, BFS/SWEA22654/SWEA22654_dohee.java
> 네
<br>
<br>
7
- 이분탐색 실전 적용 
<br>
<br>
=> [10월/3주차] 이분탐색_김도희_ver1

1. 브루트포스/BOJ14888/BOJ14888_mingyung.java, 1. 브루트포스/BOJ14889/BOJ14889_mingyung.java, 2. 그리디/BOJ11047/BOJ11047_mingyung.java, 2. 그리디/BOJ11399/BOJ11399_mingyung.java, 2. 그리디/BOJ1931/BOJ1931_mingyung.java, 2. 그리디/BOJ2839/BOJ2839_mingyung.java, 3. 구현 및 시뮬레이션/BOJ14891/BOJ14891_mingyung.java, 4. 이진탐색/BOJ10815/BOJ10815_mingyung.java, 4. 이진탐색/BOJ10816/BOJ10816_mingyung.java, 4. 이진탐색/BOJ1920/BOJ1920_mingyung.java, 4. 이진탐색/BOJ2776/BOJ2776_mingyung.java
> 공통 3문제 중 2문제, 이분 탐색 기초 5문제 중 4문제 풀었습니다.
<br>
7
<br>
- 모르겠어서 열심히 공부하면서 풀었습니다..
<br>
<br>
=> [10월/3주차] 이분탐색_박민경_ver1

2. 그리디/BOJ11047/BOJ11047_donghyeon.java, 2. 그리디/BOJ11399/BOJ11399_donghyeon.java, 2. 그리디/BOJ2839/BOJ2839_donghyeon.java
> 아니요
<br>
> 공통은 9 기초는 3
<br>
- 뭔가 열심히 한거 같은데 작동이 안된다...
<br>
<br>
=> [10월/4주차] 그리디_이동현_ver1

3. 구현 및 시뮬레이션/BOJ16236/BOJ16236_hyunjin.java, 5. 그래프/5-1. DFS, BFS/BOJ16234/BOJ16234_hyunjin.java, 5. 그래프/5-3. DIJKSTRA/BOJ11779/BOJ11779_hyunjin.java, 5. 그래프/5-3. DIJKSTRA/BOJ1446/BOJ1446_hyunjin.java, 5. 그래프/5-3. DIJKSTRA/BOJ1504/BOJ1504_hyunjin.java, 5. 그래프/5-3. DIJKSTRA/BOJ18352/BOJ18352_hyunjin.java, 5. 그래프/5-3. DIJKSTRA/BOJ2211/BOJ2211_hyunjin.java
> 아니요오...
마저 풀어서 올리겠슴다아!!
<br>
9
<br>
- 다익스트라 중간 경로를 확인하는 방법에 대해서 잘 모르겠습니다..
<br>
<br>
=> [10월/5주차] 다익스트라_김현진_ver1

1. 브루트포스/BOJ15686/BOJ15686_dohee.java, 5. 그래프/5-3. DIJKSTRA/BOJ1446/BOJ1446_dohee.java, 5. 그래프/5-3. DIJKSTRA/BOJ1504/BOJ1504_dohee.java, 5. 그래프/5-3. DIJKSTRA/BOJ18352/BOJ18352_dohee.java
=> [10월/5주차] 다익스트라_김도희_ver1

1. 브루트포스/BOJ15686/BOJ15686_wooseok.java
> 아니요
<br>
> 9
<br>
- 1번,2번
- 못풀어서 죄송해요
<br>
<br>
=> [10월/5주차] 브루트포스_송우석_ver1

1. 브루트포스/BOJ15686/BOJ15686_mingyung.java, 5. 그래프/5-3. DIJKSTRA/BOJ18352_mingyung.java
> 아니요
<br>
10
<br>
- 다익스트라 어렵고 그냥 어렵고 어려웠습니다 ㅠㅠ
<br>
<br>
=> [10월/5주차] 다익스트라_박민경_ver1

5. 그래프/5-3. DIJKSTRA/BOJ18352_mirim.java
> 아니오
<br>
10
<br>
- 
<br>
<br>
=> [10월/5주차] 다익스트라_이미림_ver1

1. 브루트포스/[BOJ]15686/[BOJ]15686_치킨배달_donghyeon.java, 5. 그래프/5-3. DIJKSTRA/[BOJ]18352/[BOJ]18352_특정거리_donghyeon.java, 7. DP/[BOJ]1446/[BOJ]1446_지름길_donghyeon.java
=> [10월/5주차] 다익스트라_이동현_ver1

3. 구현 및 시뮬레이션/BOJ16236/BOJ16236_wooseok.java, 5. 그래프/5-1. DFS, BFS/BOJ16234/BOJ16234_wooseok.java
> 네
<br>
> 7
<br>
- 아기상어 문제의 경우,  문제를 파악하는데 시간 소요가 많았습니다.
- 또한 우선순위 큐를 생각하지 못하여 문제를 푸는 과정에서 시간초과가 발생하였습니다.
<br>
<br>
=> [12월/1주차] 시뮬레이션 & BFS_송우석_ver1

3. 구현 및 시뮬레이션/BOJ16236/BOJ16236_mingyung.java, 5. 그래프/5-1. DFS, BFS/BOJ16234/BOJ16234_mingyung.java
> 네
<br>
6
<br>
- 아기상어가 생각이 바로 안났습니다...
<br>
<br>
=> [12월/1주차] 시뮬레이션 & BFS_박민경_ver1

Programmers/12월 3주차 기출문제/KAKAO_주사위고르기_hyunjin.java, Programmers/12월 3주차 기출문제/PCCP_2_hyunjin.java, Programmers/12월 3주차 기출문제/PCCP_3_hyunjin.java
> 아니요..
<br>
7
<br>
- 
<br>
<br>
=> [12월/3주차] Programmers_김현진_ver1

Programmers/12월 3주차 기출문제/KAKAO_도넛과막대그래프_mingyung.java, Programmers/12월 3주차 기출문제/KAKAO_주사위고르기_mingyung.java, Programmers/12월 3주차 기출문제/PCCP_2_mingyung.java, Programmers/12월 3주차 기출문제/PCCP_3_mingyung.java
> 네
<br>
7
<br>
- 입력 방식도 새로웠고, 뭔가 한 번 더 생각해야 하는 문제들이어서 헤맴이 있었다!
<br>
<br>
=> [12월/3주차] Programmers_박민경_ver1

Programmers/12월 3주차 기출문제/KAKAO_도넛과막대그래프_wooseok.java, Programmers/12월 3주차 기출문제/KAKAO_주사위고르기_wooseok.java, Programmers/12월 3주차 기출문제/PCCP2_wooseok.java, Programmers/12월 3주차 기출문제/PCCP_3_wooseok.java
> 네
<br>
> 4
<br>
> 문제를 이해하고 이를 어떤식으로 구상해야 하는지 어려움이 있었습니다.
- 
<br>
<br>
=> [12월/3주차] Programmers_송우석_ver1

.idea/.name, Programmers/12월 3주차 기출문제/KAKAO_도넛과막대그래프_minkyu.java, Programmers/12월 3주차 기출문제/KAKAO_주사위고르기_minkyu.java, Programmers/12월 3주차 기출문제/PCCP_2_minkyu.java, Programmers/12월 3주차 기출문제/PCCP_3_minkyu.java
> 네
<br>
3
<br>
- 그래프에서 어떻게 하면 각 그래프의 특징을 뽑아낼지에 대한 것을 캐치하는 것이 어려웠습니다.
<br>
<br>
=> [12월/3주차] Programmers_방민규_ver1

Programmers/12월 4주차 기출문제/KAKAO_산모양타일링_hyunjin.java, Programmers/12월 4주차 기출문제/KAKAO_카드게임_hyunjin.java, Programmers/12월 4주차 기출문제/PCCP_석유시추_hyunjin.java, Programmers/12월 4주차 기출문제/PCCP_아날로그시계_hyunjin.java
> 네니요
<br>
- 7
<br>
- 산 모양 타일링 DP 규칙이 잘 이해가 안 갑니다...🥲
<br>
<br>
=> [12월/4주차] 프로그래머스_김현진_ver1

Programmers/12월 4주차 기출문제/KAKAO_산모양타일링_wooseok.java, Programmers/12월 4주차 기출문제/KAKAO_카드게임_wooseok.java, Programmers/12월 4주차 기출문제/pccp_석유시추_wooseok.java, Programmers/12월 4주차 기출문제/pccp_아날로그시계_wooseok.java
> 네
<br>
> 3
<br>
- 테스트케이스의 반례에 있어 디버깅을 하는데 어려움이 있었습니다.
<br>
=> [12월/4주차] 프로그래머스_송우석_ver1

Programmers/12월 4주차 기출문제/KAKAO_산 모양 타일링_mingyung.java, Programmers/12월 4주차 기출문제/KAKAO_카드게임_mingyung.java, Programmers/12월 4주차 기출문제/PCCP_석유 시추_mingyung.java, Programmers/12월 4주차 기출문제/PCCP_아날로그 시계_mingyung.java
> 네
<br>
8
<br>
- 부동소수점의 늪에서 빠져나오기 힘들었다....
- DP는 어렵다.....
<br>
<br>
=> [12월/4주차] 프로그래머스_박민경_ver1

.idea/.name, Programmers/12월 4주차 기출문제/KAKAO_산 모양 타일링_minkyu.java, Programmers/12월 4주차 기출문제/KAKAO_카드게임_minkyu.java, Programmers/12월 4주차 기출문제/PCCP_석유 시추_minkyu.java, Programmers/12월 4주차 기출문제/PCCP_아날로그 시계_minkyu.java
=> [12월/4주차] 프로그래머스_방민규_ver1

Programmers/12월 5주차 기출문제/PCCP_수레움직이기_soomin.java, Programmers/12월 5주차 기출문제/연습_두원사이의정수쌍_soomin.java, Programmers/12월 5주차 기출문제/연습_연속된부분수열의합_soomin.java, Programmers/12월 5주차 기출문제/연습_요격시스템_soomin.java
> 네
<br>
> 3
<br>
> 자료형이나 기초적인 걸 자꾸 까먹어요
- 
<br>
<br>
=> [12월/4=5주차] 프로그래머스_김수민_ver1

Programmers/12월 5주차 기출문제/PCCP_수레움직이기_wooseok.java, Programmers/12월 5주차 기출문제/연습_두원사이의정수쌍_woosoek.java, Programmers/12월 5주차 기출문제/연습_연속된부분수열의합_wooseok.java, Programmers/12월 5주차 기출문제/연습_요격시스템_wooseok.java
> 네
<br>
4.5
<br>
> 음.. 수의 내림과 올림 매서드를 기억이 안나서 헤맸습니다.
- 
<br>
<br>
=> [12월/4=5주차] 프로그래머스_송우석_ver1[solved]

Programmers/12월 5주차 기출문제/PCCP_수레 움직이기_minkyu.java, Programmers/12월 5주차 기출문제/두 원 사이의 정수 쌍_minkyu.java, Programmers/12월 5주차 기출문제/연속된 부분 수열의 합_minkyu.java, Programmers/12월 5주차 기출문제/요격 시스템_minkyu.java
> 아니오
<br>
<br>
- 수레 움직이기 잘못된 점을 못찾겠습니다.
<br>
<br>
=> [12월/4=5주차] 프로그래머스_방민규_ver1

Programmers/12월 5주차 기출문제/PCCP_수레움직이기_hyunjin.java, Programmers/12월 5주차 기출문제/연습문제_두원사이의정수쌍_hyunjin.java, Programmers/12월 5주차 기출문제/연습문제_연속된부분수열의합_hyunjin.java, Programmers/12월 5주차 기출문제/연습문제_요격시스템_hyunjin.java
> 수레 문제 답을 못 구했습니당..
<br>
- 7 
<br>
- 
<br>
<br>
=> [12월/4=5주차] 프로그래머스_김현진_ver1

Programmers/1월 1주차 기출문제/연습_과제진행하기_hyunjin.java, Programmers/1월 1주차 기출문제/연습_광물캐기_hyunjin.java, Programmers/1월 1주차 기출문제/연습_당구연습_hyunjin.java, Programmers/1월 1주차 기출문제/연습_리코쳇로봇_hyunjin.java, Programmers/1월 1주차 기출문제/연습_연속펄스부분수열의합_hyunjin.java
> 네
<br>
- 7
<br>
- DP 생각해내는게 어려웠던 것 같습니다...🥲
<br>
<br>
=> [1월/1주차] 프로그래머스_김현진_ver1

Programmers/1월 1주차 기출문제/연습_과제진행하기_minkyu.java, Programmers/1월 1주차 기출문제/연습_광물캐기_minkyu.java, Programmers/1월 1주차 기출문제/연습_당구연습_minkyu.java, Programmers/1월 1주차 기출문제/연습_리코쳇로봇_minkyu.java, Programmers/1월 1주차 기출문제/연습_연속펄스부분수열의합_minkyu.java
> 아니오.
<br>
5
<br>
- 시간 초과 및 IDE에서는 정상 작동하나, 프로그래머스 사이트에서 작동이 제대로 되지 않음
<br>
<br>
=> [1월/1주차] 프로그래머스_방민규_ver1.0

Programmers/1월 1주차 기출문제/연습_과제진행하기_wooseok.java, Programmers/1월 1주차 기출문제/연습_광물캐기_wooseok.java, Programmers/1월 1주차 기출문제/연습_당구연습_wooseok.java, Programmers/1월 1주차 기출문제/연습_리코쳇로봇_wooseok.java, Programmers/1월 1주차 기출문제/연습_연속펄스부분수열의합_wooseok.java
=> [1월/1주차] 프로그래머스_송우석_ver1

Programmers/1월 2주차 기출문제/연습_무인도여행_mingyung.java, Programmers/1월 2주차 기출문제/연습_미로탈출_mingyung.java, Programmers/1월 2주차 기출문제/연습_호텔대실_mingyung.java, Programmers/1월 2주차 기출문제/연습_혼자서하는틱택토_mingyung.java
> 네
<br>
4
<br>
- 틱택토 조건 찾기가 조금 까다로웠습니다!
<br>
<br>
=> [1월/2주차] 프로그래머스_박민경_ver1

Programmers/1월 2주차 기출문제/연습_무인도여행_soomin.java, Programmers/1월 2주차 기출문제/연습_미로탈출_soomin.java, Programmers/1월 2주차 기출문제/연습_호텔대실_soomin.java, Programmers/1월 2주차 기출문제/연습_혼자서하는틱택토_soomin.java
> 네
<br>
> 2
<br>
- * 입출력을 조심하자
<br>
<br>
=> [1월/2주차] 프로그래머스_김수민_ver1

Programmers/1월 2주차 기출문제/연습_무인도여행_minkyu.java, Programmers/1월 2주차 기출문제/연습_미로탈출_minkyu.java, Programmers/1월 2주차 기출문제/연습_호텔대실_minkyu.java, Programmers/1월 2주차 기출문제/연습_혼자서하는틱택토_minkyu.java
=> [1월/2주차] 프로그래머스_방민규_ver1

Programmers/1월 2주차 기출문제/연습_무인도여행_hyunjin.java, Programmers/1월 2주차 기출문제/연습_미로탈출_hyunjin.java, Programmers/1월 2주차 기출문제/연습_호텔대실_hyunjin.java, Programmers/1월 2주차 기출문제/연습_혼자서하는틱택토_hyunjin.java
> 네
<br>
> 4
<br>
- 
<br>
<br>
=> [1월/2주차] 프로그래머스_김현진_ver1

Programmers/1월 2주차 기출문제/연습_무인도여행_wooseok.java, Programmers/1월 2주차 기출문제/연습_미로탈출_wooseok.java, Programmers/1월 2주차 기출문제/연습_호텔대실_wooseok.java, Programmers/1월 2주차 기출문제/연습_혼자서하는틱택토_wooseok.java
=> [1월/2주차] 프로그래머스_송우석_ver1

Programmers/1월 3주차 기출문제/KAKAO_택배배달과수거하기_minkyu.java, Programmers/1월 3주차 기출문제/KAKAO_표현가능한이진트리_minkyu.java, Programmers/1월 3주차 기출문제/연습_뒤에있는큰수찾기_minkyu.java, Programmers/1월 3주차 기출문제/연습_숫자변환하기_minkyu.java, Programmers/1월 4주차 기출문제/KAKAO_이모티콘할인행사_minkyu.java, Programmers/1월 4주차 기출문제/KAKAO_표병합_minkyu.java, Programmers/1월 4주차 기출문제/연습_시소짝꿍_minkyu.java, Programmers/1월 4주차 기출문제/연습_인사고과_minkyu.java
> 네
<br>
5
<br>
- 표현 가능한 이진트리 런타임 에러를 어떻게 해결해야될지 확인중입니다.
<br>
<br>
=> [1월/4주차] 프로그래머스_방민규_ver1.0

Programmers/1월 3주차 기출문제/KAKAO_택배배달과수거하기_soomin.java, Programmers/1월 3주차 기출문제/KAKAO_표현가능한이진트리_soomin.java, Programmers/1월 3주차 기출문제/연습_뒤에있는큰수찾기_soomin.java, Programmers/1월 3주차 기출문제/연습_숫자변환하기_soomin.java, Programmers/1월 4주차 기출문제/KAKAO_이모티콘할인행사_soomin.java, Programmers/1월 4주차 기출문제/KAKAO_표병합_soomin.java, Programmers/1월 4주차 기출문제/연습_시소짝꿍_soomin.java, Programmers/1월 4주차 기출문제/연습_인사고과_soomin.java
> 아니오
<br>
> 7
<br>
- 풀이 아이디어 떠올리기, 분할정복 구현
- 표 병합 계속 런타임 에러 나는데 어디가 틀린지 모르겠어요
<br>
<br>
=> [1월/3,4주차] 프로그래머스_김수민_ver1

Programmers/1월 3주차 기출문제/KAKAO_택배배달과수거하기_wooseok.java, Programmers/1월 3주차 기출문제/KAKAO_표현가능한이진트리_wooseok.java, Programmers/1월 3주차 기출문제/연습_뒤에있는큰수찾기_wooseok.java, Programmers/1월 3주차 기출문제/연습_숫자변환하기_wooseok.java
> 네
<br>
> 6
<br>
- 문제를 풀기위한 구상 난이도가 어려웠다. 어떤 방식으로 풀어나가야 하는지 고민하는 시간이 길었다.
<br>
<br>
=> [1월/3주차] 프로그래머스_송우석_ver1

Programmers/1월 3주차 기출문제/KAKAO_택배배달과수거하기_hyunjin.java, Programmers/1월 3주차 기출문제/KAKAO_표현가능한이진트리_hyunjin.java, Programmers/1월 3주차 기출문제/연습_뒤에있는큰수찾기_hyunjin.java, Programmers/1월 3주차 기출문제/연습_숫자변환하기_hyunjin.java, Programmers/1월 4주차 기출문제/KAKAO_표병합_hyunjin.java, Programmers/1월 4주차 기출문제/KAKAO_표현가능한이진트리_hyunjin.java, Programmers/1월 4주차 기출문제/연습_시소짝꿍_hyunjin.java, Programmers/1월 4주차 기출문제/연습_인사고과_hyunjin.java
> 네
카카오 문제는 어려워서 풀이 참고 했습니다...🥲
<br>
8
<br>
- 혼자서 풀이 과정의 전반적인 흐름을 이끌어 내는게 어려웠습니다.. 풀이를 보면 이해가 가는데 혼자 생각해 내기가 어려움...😭😭😭
<br>
<br>
=> [1월/3,4주차] 프로그래머스_김현진_ver1

Programmers/1월 3주차 기출문제/KAKAO_택배배달과수거하기_mingyung.java, Programmers/1월 3주차 기출문제/KAKAO_표현가능한이진트리_mingyung.java, Programmers/1월 3주차 기출문제/연습_뒤에있는큰수찾기_mingyung.java, Programmers/1월 3주차 기출문제/연습_숫자변환하기_mingyung.java, Programmers/1월 4주차 기출문제/KAKAO_이모티콘할인행사_mingyung.java, Programmers/1월 4주차 기출문제/KAKAO_표병합_mingyung.java, Programmers/1월 4주차 기출문제/연습_시소짝꿍_mingyung.java, Programmers/1월 4주차 기출문제/연습_인사고과_mingyung.java
> 네
<br>
8
<br>
- 이진트리 너무 어렵다...  프로젝트 너무 힘들다...
<br>
<br>
=> [1월/3주차] 프로그래머스_박민경_ver1

Programmers/1월 3주차 기출문제/KAKAO_택배배달과수거하기_wooseok.java, Programmers/1월 3주차 기출문제/KAKAO_표현가능한이진트리_wooseok.java, Programmers/1월 3주차 기출문제/연습_뒤에있는큰수찾기_wooseok.java, Programmers/1월 3주차 기출문제/연습_숫자변환하기_wooseok.java, Programmers/1월 4주차 기출문제/KAKAO_이모티콘할인행사_wooseok.java, Programmers/1월 4주차 기출문제/KAKAO_표병합_wooseok.java, Programmers/1월 4주차 기출문제/연습_시소짝궁_wooseok.java, Programmers/1월 4주차 기출문제/연습_인사고과_wooseok.java
> 네
<br>
> 7
<br>
- 문제를 이해하고 어떻게 풀어가야하는지 어려웠습니다.
<br>
=> [1월/3,4주차] 프로그래머스_송우석_ver1

Programmers/1월 3주차 기출문제/KAKAO_택배배달과수거하기_mirim.java, Programmers/1월 3주차 기출문제/KAKAO_표현가능한이진트리_mirim.java, Programmers/1월 3주차 기출문제/연습_뒤에있는큰수찾기_mirim.java, Programmers/1월 3주차 기출문제/연습_숫자변환하기_mirim.java, Programmers/1월 4주차 기출문제/KAKAO_이모티콘할인행사_mirim.java, Programmers/1월 4주차 기출문제/KAKAO_표병합_mirim.java, Programmers/1월 4주차 기출문제/연습_시소짝궁_mirim.java, Programmers/1월 4주차 기출문제/연습_인사고과_mirim.java
> 네
<br>
9
<br>
- 알고리즘린이는 모든 문제가 겁이나요
<br>
<br>
=> [1월/3,4주차] 프로그래머스_이미림_ver1

Programmers/2월 1주차 기출문제/KAKAO_미로탈출명령어_mingyung.java, Programmers/2월 1주차 기출문제/연습_마법의엘리베이터_mingyung.java
> 네
<br>
5
<br>
- 카카오... 접근법을 대충 알겠는데, 구현하기 어려웠다! 고민할 점이 많았음.. 정보 찾아봄!
- 연습문제는 무난했다.
<br>
<br>
=> [2월/1주차] 프로그래머스_박민경_ver1

Programmers/2월 1주차 기출문제/KAKAO_미로탈출명령어_minkyu.java, Programmers/2월 1주차 기출문제/연습_마법의엘리베이터_minkyu.java
=> [2월/1주차] 프로그래머스_방민규_ver1.0

Programmers/2월 1주차 기출문제/KAKAO_미로탈출명령어_wooseok.java, Programmers/2월 1주차 기출문제/연습_마법의엘리베이터_wooseok.java
=> [2월/1주차] 프로그래머스_송우석_ver1

Programmers/2월 1주차 기출문제/KAKAO_미로탈출명령어_hyunjin.java, Programmers/2월 1주차 기출문제/연습_마법의엘리베이터_hyunjin.java
> 네
<br>
8
<br>
- 알듯말듯하면서 안 풀려요.. 정답 코드보고 이해했습니다ㅜㅜ
<br>
<br>
=> [2월/1주차] 프로그래머스_김현진_ver1

Programmers/2월 4주차 기출문제/KAKAO_등산코스정하기_hyunjin.java, Programmers/2월 4주차 기출문제/KAKAO_코딩테스트공부_hyunjin.java, Programmers/2월 4주차 기출문제/연습_디펜스게임_hyunjin.java, Programmers/2월 4주차 기출문제/연습_점찍기_hyunjin.java
> 네
<br>
8
<br>
- 오랜만에 다익스트라 문제 풀려고 하니까 기억이 나지 않아요...
<br>
<br>
=> [2월/4주차] 프로그래머스_김현진_ver1

Programmers/2월 4주차 기출문제/KAKAO_등산코스정하기_wooseok.java, Programmers/2월 4주차 기출문제/KAKAO_코딩테스트공부_wooseok.java, Programmers/2월 4주차 기출문제/연습__디펜스게임wooseok.java, Programmers/2월 4주차 기출문제/연습_점찍기_wooseok.java
> 네
<br>
>5
<br>
> 등산코스 정하기 문제에서 정렬하는 코드를 중간에 넣지 않아서 제대로 결과가 안나오는 경우가 있었음 
- 
<br>
<br>
=> [2월/4주차] 프로그래머스_송우석_ver1

Programmers/2월 4주차 기출문제/KAKAO_등산코스정하기_mingyung.java, Programmers/2월 4주차 기출문제/KAKAO_코딩테스트공부_mingyung.java, Programmers/2월 4주차 기출문제/연습_디펜스게임_mingyung.java, Programmers/2월 4주차 기출문제/연습_점찍기_mingyung.java
> 아니요.. 등산코스 틀림!
<br>
8
<br>
- 다익스트라 어렵다.. 카카오 어렵다!
<br>
<br>
=> [2월/4주차] 프로그래머스_박민경_ver1

Programmers/2월 4주차 기출문제/KAKAO_등산코스정하기_minkyu.java, Programmers/2월 4주차 기출문제/KAKAO_코딩테스트공부_minkyu.java, Programmers/2월 4주차 기출문제/연습_디펜스게임_minkyu.java, Programmers/2월 4주차 기출문제/연습_점찍기_minkyu.java
> 네
<br>
6
<br>
- 코딩테스트 공부에서 dp 발상을 하는게 좀 어려웠습니다.
<br>
<br>
=> [2월/4주차] 프로그래머스_방민규_ver1

Programmers/3월 1주차 기출문제/KAKAO_두큐합같게만들기_mingyung.java, Programmers/3월 1주차 기출문제/연습_귤고르기_mingyung.java, Programmers/3월 1주차 기출문제/연습_숫자타자대회_mingyung.java, Programmers/3월 1주차 기출문제/연습_억억단을외우자_mingyung.java
=> [3월/1주차] 프로그래머스_박민경_ver1

Programmers/3월 1주차 기출문제/KAKAO_두큐합같게만들기_Maxwithjude.java, Programmers/3월 1주차 기출문제/연습_귤고르기_Maxwithjude.java, Programmers/3월 1주차 기출문제/연습_숫자타자대회_Maxwithjude.java
=> [3월/1주차] 프로그래머스_이동현_ver1

Programmers/3월 1주차 기출문제/KAKAO_두큐합같게만들기_soomin.java, Programmers/3월 1주차 기출문제/연습_귤고르기_soomin.java, Programmers/3월 1주차 기출문제/연습_숫자타자대회_soomin.java, Programmers/3월 1주차 기출문제/연습_억억단을외우자_soomin.java
> 아니요
<br>
> 6
<br>
> 수학공부 다시 해야될 거 같아요
- 
<br>
<br>
=> [3월/1주차] 프로그래머스_김수민_ver1

Programmers/3월 1주차 기출문제/KAKAO_두큐합같게만들기_minkyu.java, Programmers/3월 1주차 기출문제/연습_귤고르기_minkyu.java, Programmers/3월 1주차 기출문제/연습_숫자타자대회_minkyu.java, Programmers/3월 1주차 기출문제/연습_억억단을외우자_minkyu.java
> 네
<br>
7
<br>
- 숫자 패드에서 dp로의 풀이 방법을 생각해내는 것이 어려웠습니다.
<br>
<br>
=> [3월/1주차] 프로그래머스_방민규_ver1

Programmers/3월 2주차 기출문제/연습_등대_Maxwithjude.java, Programmers/3월 2주차 기출문제/연습_숫자카드나누기_Maxwithjude.java, Programmers/3월 2주차 기출문제/연습_우박수열정적분_Maxwithjude.java
> 아니오
<br>
<br> 7
- 
<br>
<br>
=> [3월/2주차] 프로그래머스_이동현_ver1

Programmers/3월 2주차 기출문제/KAKAO_사라지는벌판_hyunjin.java, Programmers/3월 2주차 기출문제/연습_등대_hyunjin.java, Programmers/3월 2주차 기출문제/연습_숫자카드나누기_hyunjin.java, Programmers/3월 2주차 기출문제/연습_우박수열정적분_hyunjin.java
> 네니요
<br>
8
<br>
- 카카오 사라지는 발판 문제 dfs 구조와 턴수 계산하는 부분 코드가 완벽하게 이해되지 않는 것 같습니다.. 참고 자료 많이 찾아봄
<br>
카카오 이 분 풀이 참고!
[https://howudong.tistory.com/409](https://howudong.tistory.com/409)
<br>
=> [3월/2주차] 프로그래머스_김현진_ver1

Programmers/3월 2주차 기출문제/KAKAO_사라지는발판_mingyung.java, Programmers/3월 2주차 기출문제/연습_등대_mingyung.java, Programmers/3월 2주차 기출문제/연습_숫자카드나누기_mingyung.java, Programmers/3월 2주차 기출문제/연습_우박수열정적분_mingyung.java
> 네.. 열심히 찾아서 공부했습니다.
<br>
10..
<br>
- 정적분이 뭐였드라에서 시작된 어려움..... 그냥 다 어려움.....
<br>
<br>
=> [3월/2주차] 프로그래머스_박민경_ver1

Programmers/3월 2주차 기출문제/KAKAO_사라지는발판_soomin.java, Programmers/3월 2주차 기출문제/연습_등대_soomin.java, Programmers/3월 2주차 기출문제/연습_숫자카드나누기_soomin.java, Programmers/3월 2주차 기출문제/연습_우박수열정적분_soomin.java
> 카카오 이거 뭐예요...?
<br>
> 7
<br>
- GCD 구하는 로직을 잊어버렸어요
- 카카오 문제를 아직 이해하지 못했습니다
<br>
<br>
=> [3월/2주차] 프로그래머스_김수민_ver1

Programmers/3월 2주차 기출문제/KAKAO_사라지는발판_minkyu.java, Programmers/3월 2주차 기출문제/연습_등대_minkyu.java, Programmers/3월 2주차 기출문제/연습_숫자카드나누기_minkyu.java, Programmers/3월 2주차 기출문제/연습_우박수열정적분_minkyu.java
> 네
<br>
7
<br>
- 사라지는 발판의 번갈아가면서 진행하는 턴을 구현하기 어려웠습니다.
<br>
<br>
=> [3월/2주차] 프로그래머스_방민규_ver1

Programmers/3월 3주차 기출문제/KAKAO_파괴되지않은건물_Maxwithjude.java, Programmers/3월 3주차 기출문제/연습_롤케이크자르기_Maxwithjude.java, Programmers/3월 3주차 기출문제/연습_부대복귀_Maxwithjude.java, Programmers/3월 3주차 기출문제/연습_택배상자_Maxwithjude.java
> 네
<br>
<br>
-  카카오 문제 효율성 테스트 무엇..
<br>
<br>
=> [3월/3주차] 프로그래머스_이동현_ver1

Programmers/3월 3주차 기출문제/KAKAO_파괴되지않은건물_soomin.java, Programmers/3월 3주차 기출문제/연습_롤케이크자르기_soomin.java, Programmers/3월 3주차 기출문제/연습_부대복귀_soomin.java, Programmers/3월 3주차 기출문제/연습_택배상자_soomin.java, Programmers/3월 4주차 기출문제/KAKAO_양궁대회_soomin.java, Programmers/3월 4주차 기출문제/연습_2차원동전뒤집기_soomin.java
> 네
<br>
> 6
<br>
- 잘 안 풀다보니 알고리즘 바보가 되었습니다
<br>
<br>
=> [3월/3,4주차] 프로그래머스_김수민_ver1

Programmers/3월 3주차 기출문제/KAKAO_파괴되지않은건물_hyunjin.java, Programmers/3월 3주차 기출문제/연습_롤케이크자르기_hyunjin.java, Programmers/3월 3주차 기출문제/연습_부대복귀_hyunjin.java, Programmers/3월 3주차 기출문제/연습_택배상자_hyunjin.java
> 네
<br>
6
<br>
- 카카오 문제에서 누적합에 대해서 생각하고 이해하는 과정이 좀 어려웠습니다..! 다음에 또 나오면 과연 풀 수 있을까 싶은 느낌ㅠㅠ
<br>
- 2차원 배열 누적합 개념 이해하기
[https://sweets1327.tistory.com/30](https://sweets1327.tistory.com/30)
[https://nahwasa.com/entry/%EB%88%84%EC%A0%81-%ED%95%A9prefix-sum-2%EC%B0%A8%EC%9B%90-%EB%88%84%EC%A0%81%ED%95%A9prefix-sum-of-matrix-with-java](https://nahwasa.com/entry/%EB%88%84%EC%A0%81-%ED%95%A9prefix-sum-2%EC%B0%A8%EC%9B%90-%EB%88%84%EC%A0%81%ED%95%A9prefix-sum-of-matrix-with-java)
<br>
=> [3월/3주차] 프로그래머스_김현진_ver1

Programmers/3월 3주차 기출문제/KAKAO_파괴되지않은건물_mingyung.java, Programmers/3월 3주차 기출문제/연습_롤케이크자르기_mingyung.java, Programmers/3월 3주차 기출문제/연습_부대복귀_mingyung.java, Programmers/3월 3주차 기출문제/연습_택배상자_mingyung.java
> 네
<br>
7
<br>
- 카카오... 재밌다.....
<br>
<br>
=> [3월/3주차] 프로그래머스_박민경_ver1

Programmers/3월 3주차 기출문제/KAKAO_파괴되지않은건물_minkyu.java, Programmers/3월 3주차 기출문제/연습_롤케이크자르기_minkyu.java, Programmers/3월 3주차 기출문제/연습_부대복귀_minkyu.java, Programmers/3월 3주차 기출문제/연습_택배상자_minkyu.java
=> [3월/3주차] 프로그래머스_방민규_ver1

Programmers/3월 2주차 기출문제/KAKAO_사라지는발판_wooseok.java, Programmers/3월 2주차 기출문제/연습_등대_wooseok.java, Programmers/3월 2주차 기출문제/연습_숫자카드나누기_wooseok.java, Programmers/3월 2주차 기출문제/연습_우박수열정적분_wooseok.java, Programmers/3월 3주차 기출문제/KAKAO_파괴되지않은건물_wooseok.java, Programmers/3월 3주차 기출문제/연습_롤케이크자르기_wooseok.java, Programmers/3월 3주차 기출문제/연습_부대복귀_woosoek.java, Programmers/3월 3주차 기출문제/연습_택배상자_wooseok.java
=> [3월/3주차] 프로그래머스_송우석_ver1

Programmers/3월 4주차 기출문제/KAKAO_양궁대회_hyunjin.java, Programmers/3월 4주차 기출문제/연습_2차원동전뒤집기_hyunjin.java
> 네
<br>
- 7
<br>
- 
<br>
<br>
=> [3월/4주차] 프로그래머스_김현진_ver1

Programmers/3월 4주차 기출문제/KAKAO_양궁대회_mingyung.java, Programmers/3월 4주차 기출문제/연습_2차원동전뒤집기_mingyung.java
> 네
<br>
7
<br>
- 프로젝트 화이팅!
<br>
<br>
=> [3월/4주차] 프로그래머스_박민경_ver1

Programmers/3월 4주차 기출문제/연습_2차원동전뒤집기_Maxwithjude.java
> 아니요
<br>
8
<br>
- 머리가 초기화 되어서 다 어려워요 ㅎㅎ
<br>
<br>
=> [3월/4주차] 프로그래머스_이동현_ver1

Programmers/3월 1주차 기출문제/KAKAO_두큐합같게만들기_mirim.java, Programmers/3월 1주차 기출문제/연습_귤고르기_mirim.java, Programmers/3월 4주차 기출문제/KAKAO_양궁대회_mirim.java, Programmers/3월 4주차 기출문제/연습_2차원동전뒤집기_mirim.java
> 네
<br>
> 8
<br>
- 
<br>
<br>
=> [3월/4주차] 프로그래머스_이미림_ver1

Programmers/4월 3주차 기출문제/KAKAO_양과늑대_soomin.java, Programmers/4월 3주차 기출문제/연습_연속부분수열합의개수_soomin.java, Programmers/4월 3주차 기출문제/연습_카운트다운_soomin.java, Programmers/4월 3주차 기출문제/연습_혼자놀기의달인_soomin.java
> 네
<br>
> 5
<br>
- DP 어려워요
<br>
<br>
=> [4월/3주차] 프로그래머스_김수민_ver1

Programmers/4월 3주차 기출문제/KAKAO_양과늑대_mingyung.java, Programmers/4월 3주차 기출문제/연습_연속부분수열합의개수_mingyung.java, Programmers/4월 3주차 기출문제/연습_카운트다운_mingyung.java, Programmers/4월 3주차 기출문제/연습_혼자놀기의달인_mingyung.java
> 네! 모르겠는 부분 찾아서 풀었습니다.
<br>
8
<br>
- dp는 어렵다.... 카카오는 쉽지 않다!
<br>
<br>
=> [4월/3주차] 프로그래머스_박민경_ver1

Programmers/4월 3주차 기출문제/연습_연속부분수열합의개수_hyunjin.java, Programmers/4월 3주차 기출문제/연습_카운트다운_hyunjin.java, Programmers/4월 3주차 기출문제/연습_혼자놀기의달인_hyunjin.java
> 아니요..
(오늘 정처기 실기 시험으로 인해 문제를 다 풀지는 못 했슴니다.. 죄송합니다🥲)
<br>
- 8
<br>
- 다트 문제 그리디로 접근하려다가 처참히 실패했는데, 이차원 DP 써서 푸는 부분이 어려웠습니😭
<br>
<br>
=> [4월/3주차] 프로그래머스_김현진_ver1

Programmers/4월 3주차 기출문제/KAKAO_양과늑대_minkyu.java, Programmers/4월 3주차 기출문제/연습_연속부분수열합의개수_minkyu.java, Programmers/4월 3주차 기출문제/연습_카운트다운_minkyu.java, Programmers/4월 3주차 기출문제/연습_혼자놀기의달인_minkyu.java
=> [4월/3주차] 프로그래머스_방민규_ver1

Programmers/4월 3주차 기출문제/연습_연속부분수열합의개수_MaxwithJude.java, Programmers/4월 3주차 기출문제/연습_카운트다운_MaxwithJude.java, Programmers/4월 3주차 기출문제/연습_혼자놀기의달인_MaxwithJude.java
> 아니요
<br>
8
<br>
- 
<br>
<br>
=> [4월/3주차] 프로그래머스_이동현_ver1

Programmers/4월 4주차 기출문제/KAKAO_k진수에서소수개수구하기_minkyu.java, Programmers/4월 4주차 기출문제/KAKAO_주차요금계산_minkyu.java, Programmers/4월 4주차 기출문제/연습_할인행사_minkyu.java, Programmers/4월 4주차 기출문제/완전탐색_피로도_minkyu.java
> 네
<br>
4
<br>
- 주차 요금 문제가 좀 헷갈려서 시간이 걸렸습니다.
<br>
<br>
=> [4월/4주차] 프로그래머스_방민규_ver1

Programmers/4월 4주차 기출문제/KAKAO_k진수에서소수개수구하기_soomin.java, Programmers/4월 4주차 기출문제/KAKAO_주차요금계산_soomin.java, Programmers/4월 4주차 기출문제/연습_피로도_soomin.java, Programmers/4월 4주차 기출문제/연습_할인행사_soomin.java
> 네
<br>
> 4
<br>
- k진수로 바꾸는 로직이나 순열 로직이 약간 헷갈렸어요
<br>
<br>
=> [4월/4주차] 프로그래머스_김수민_ver1

Programmers/4월 4주차 기출문제/KAKAO_k진수에서소수개수구하기_wooseok.java, Programmers/4월 4주차 기출문제/KAKAO_주차요금계산_wooseok.java, Programmers/4월 4주차 기출문제/연습_할인행사_wooseok.java, Programmers/4월 4주차 기출문제/완전탐색_피로도_wooseok.java
> 네
<br>
4
<br>
- 해시맵 사용법을 생각해내는데 시간이 조금 소요되었습니다.
<br>
<br>
=> [4월/4주차] 프로그래머스_송우석_ver1

Programmers/4월 4주차 기출문제/연습_피로도_Maxwithjude.java, Programmers/4월 4주차 기출문제/연습_할인행사_Maxwithjude.java, Programmers/4월 4주차 기출문제/카카오_k진수에서소수개수구하기_Maxwithjude.java
> 아니오
<br>
<br> 8
- 
<br>
<br>
=> [4월/4주차] 프로그래머스_이동현_ver1
